import { authService } from './auth'
import { demoApi, isDemoMode } from './demo'
const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000/api/v1').replace(/\/$/, '')
export class ApiError extends Error { constructor(message,status=0){super(message);this.name='ApiError';this.status=status} }
export async function apiRequest(path,options={}) { const user=authService.getCurrentUser();if(!user)throw new ApiError('Your session has ended. Please sign in again.',401);const token=await user.getIdToken();let response;try{response=await fetch(`${API_BASE_URL}${path}`,{...options,headers:{Accept:'application/json',Authorization:`Bearer ${token}`,...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}})}catch{throw new ApiError('Network unavailable. Your work is saved on this device where possible.')}if(response.status===401){window.dispatchEvent(new Event('sparsh:unauthorized'));throw new ApiError('Your session has expired. Please sign in again.',401)}if(response.ok)return response.status===204?null:response.json();const payload=await response.json().catch(()=>null);const detail=payload?.detail;throw new ApiError(typeof detail==='object'?detail.message||`Request failed (${response.status})`:detail||`Request failed (${response.status})`,response.status) }
const live={users:{getMe:()=>apiRequest('/users/me'),list:()=>apiRequest('/users'),create:data=>apiRequest('/users',{method:'POST',body:JSON.stringify(data)}),update:(uid,data)=>apiRequest(`/users/${uid}`,{method:'PATCH',body:JSON.stringify(data)}),setActivation:(uid,disabled)=>apiRequest(`/users/${uid}/activation`,{method:'PATCH',body:JSON.stringify({disabled})})},centres:{list:()=>apiRequest('/centres'),create:data=>apiRequest('/centres',{method:'POST',body:JSON.stringify(data)}),update:(centreId,data)=>apiRequest(`/centres/${centreId}`,{method:'PATCH',body:JSON.stringify(data)})},children:{list:()=>apiRequest('/children'),get:id=>apiRequest(`/children/${id}`),create:data=>apiRequest('/children',{method:'POST',body:JSON.stringify(data)}),healthData:(id,data)=>apiRequest(`/children/${id}/health-data`,{method:'POST',body:JSON.stringify(data)}),healthHistory:id=>apiRequest(`/children/${id}/health-data`),history:id=>apiRequest(`/children/${id}/history`)},screenings:{milestones:childId=>apiRequest(`/children/${childId}/milestones`),submit:data=>apiRequest('/screenings',{method:'POST',body:JSON.stringify(data)}),risk:id=>apiRequest(`/screenings/${id}/risk`)},referrals:{create:data=>apiRequest('/referrals',{method:'POST',body:JSON.stringify(data)}),get:id=>apiRequest(`/referrals/${id}`),byScreening:screeningId=>apiRequest(`/referrals/screening/${screeningId}`)}}
const choose = (name) =>
  new Proxy({}, {
    get: (_, prop) =>
      (...args) => {
        const fn = isDemoMode() ? demoApi[name][prop] : live[name][prop]
        return typeof fn === 'function' ? fn(...args) : fn
      }
  })
export const usersApi=choose('users');export const centresApi=choose('centres');export const childrenApi=choose('children');export const screeningsApi=choose('screenings');export const referralsApi=choose('referrals')
