import { useEffect, useMemo, useState } from 'react'
import Button from '../components/Button'
import { ErrorState, LoadingState, EmptyState } from '../components/AsyncState'
import { screeningsApi } from '../services/api'
import { cacheMilestones, clearDraft, getCachedMilestones, loadDraft, saveDraft } from '../services/offline'
import { useApp } from '../context/AppContext'

const labels={gross_motor:'Gross Motor',fine_motor:'Fine Motor',language:'Language',social_emotional:'Social-Emotional',cognitive:'Cognitive'}

export default function ScreeningScreen({onNavigate}) {
  const {currentChild,setPendingScreening}=useApp(); const [data,setData]=useState(null); const [error,setError]=useState(null)
  const [answers,setAnswers]=useState({}); const [domain,setDomain]=useState(0)
  const load=async()=>{if(!currentChild)return;setError(null);try{const result=await screeningsApi.milestones(currentChild.id);cacheMilestones(currentChild.id,result);setData(result)}catch(e){const cached=getCachedMilestones(currentChild.id);if(cached){setData(cached);setError(new Error('You are offline. Using the last saved questions; reconnect before submitting.'))}else setError(e)}}
  useEffect(()=>{setData(null);setAnswers({});setDomain(0);load()},[currentChild?.id])
  useEffect(()=>{if(!currentChild||!data)return;const draft=loadDraft();if(draft?.childId===currentChild.id&&draft.checkpointAgeMonths===data.checkpoint_age_months&&draft.datasetVersion===data.dataset_version)setAnswers(draft.answers||{})},[currentChild?.id,data?.checkpoint_age_months,data?.dataset_version])
  useEffect(()=>{if(currentChild&&data)saveDraft({childId:currentChild.id,checkpointAgeMonths:data.checkpoint_age_months,datasetVersion:data.dataset_version,answers})},[answers,currentChild?.id,data])
  const domains=useMemo(()=>[...new Set(data?.milestones?.map(m=>m.domain)||[])],[data]); const tasks=data?.milestones?.filter(m=>m.domain===domains[domain])||[]
  const total=data?.milestones?.length||0; const unanswered=data?.milestones?.filter(m=>!answers[m.id])||[]; const count=total-unanswered.length
  const answer=(id,response)=>setAnswers(a=>({...a,[id]:response}))
  const advance=()=>{if(tasks.some(t=>!answers[t.id]))return;if(domain<domains.length-1){setDomain(d=>d+1);return}setPendingScreening({child_id:currentChild.id,checkpoint_age_months:data.checkpoint_age_months,milestone_dataset_version:data.dataset_version,client_submission_id:crypto.randomUUID(),answers:data.milestones.map(({id})=>({milestone_id:id,response:answers[id]})),screened_at:new Date().toISOString()});clearDraft();onNavigate('av-assessment')}
  if(!currentChild)return <main className="grid min-h-screen place-items-center bg-neutral-50 p-6"><EmptyState title="Choose a child first" detail="Register a child or open an existing record before screening." action={<Button className="mt-4" onClick={()=>onNavigate('records')}>View children</Button>}/></main>
  if(!data&&!error)return <LoadingState label="Loading age-appropriate milestones…"/>
  if(!data)return <main className="p-5"><ErrorState error={error} onRetry={load}/></main>
  return <main className="min-h-screen bg-primary-950 p-4 pb-8"><header className="mx-auto flex max-w-xl items-center justify-between py-3 text-white"><button onClick={()=>onNavigate('dashboard')} className="min-h-11 min-w-11">←</button><div className="text-center"><h1 className="font-bold">Development Screening</h1><p className="text-xs text-white/70">{currentChild.name} · {data.current_age_months} months</p></div><span className="text-xs font-bold">{count}/{total}</span></header><section className="mx-auto max-w-xl rounded-3xl bg-white p-5"><div className="mb-5 h-2 rounded-full bg-primary-100"><div className="h-full rounded-full bg-teal-600" style={{width:`${total?count/total*100:0}%`}}/></div>{error&&<p className="mb-4 rounded-lg bg-amber-50 p-2 text-xs text-amber-800">{error.message}</p>}<p className="text-xs font-bold uppercase tracking-wide text-teal-700">Domain {domain+1} of {domains.length}</p><h2 className="mt-1 text-xl font-extrabold">{labels[domains[domain]]||domains[domain]}</h2><div className="mt-5 space-y-3">{tasks.map(task=><article key={task.id} className={`rounded-2xl border p-4 ${!answers[task.id]?'border-amber-300':''}`}><p className="font-semibold text-neutral-800">{task.task||task.description||task.label}</p><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={()=>answer(task.id,'YES')} className={`min-h-11 rounded-xl border font-bold ${answers[task.id]==='YES'?'border-emerald-600 bg-emerald-600 text-white':'border-emerald-200 text-emerald-700'}`}>Yes</button><button onClick={()=>answer(task.id,'NO')} className={`min-h-11 rounded-xl border font-bold ${answers[task.id]==='NO'?'border-red-600 bg-red-600 text-white':'border-red-200 text-red-700'}`}>No</button><button onClick={()=>answer(task.id,'UNSURE')} className={`min-h-11 rounded-xl border font-bold ${answers[task.id]==='UNSURE'?'border-amber-600 bg-amber-600 text-white':'border-amber-200 text-amber-700'}`}>Unsure</button></div>{!answers[task.id]&&<p className="mt-2 text-xs text-amber-800">Response required</p>}</article>)}</div><div className="mt-5 flex gap-3"><Button variant="secondary" disabled={!domain} onClick={()=>setDomain(d=>d-1)}>Back</Button><Button className="flex-1" onClick={advance} disabled={tasks.some(t=>!answers[t.id])}>{domain===domains.length-1?'Continue to A/V':'Next domain'}</Button></div>{domain===domains.length-1&&unanswered.length>0&&<p className="mt-3 text-sm text-amber-800">{unanswered.length} question{unanswered.length===1?' remains':'s remain'} unanswered.</p>}</section></main>
}
